services:
  redpanda:
    image: redpandadata/redpanda:latest
    command: >
      redpanda start
      --overprovisioned --smp 1 --memory 1G --reserve-memory 0M
      --node-id 0 --check=false
      --kafka-addr PLAINTEXT://0.0.0.0:9092
      --advertise-kafka-addr PLAINTEXT://redpanda:9092
      --rpc-addr 0.0.0.0:33145
      --advertise-rpc-addr redpanda:33145
    ports: ["9092:9092"]
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:9644/v1/status/ready >/dev/null"]
      interval: 5s
      timeout: 5s
      retries: 30

  clickhouse:
    image: clickhouse/clickhouse-server:24.8
    environment:
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_USER=netintel
      - CLICKHOUSE_PASSWORD=netintel_pwd
      - CLICKHOUSE_DB=default
    ports: ["9000:9000","8123:8123"]
    healthcheck:
      test: ["CMD-SHELL", "clickhouse-client --host localhost --query 'SELECT 1' || wget -qO- http://localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 18

  collector:
    build: { context: .., dockerfile: deploy/Dockerfile.collector }
    environment:
      - APP_NAME=collector
      - HTTP_ADDR=:8080
      - METRICS_ADDR=:9090
      - KAFKA_BROKERS=redpanda:9092
      - KAFKA_TOPIC=netintel.events.v1
    depends_on:
      redpanda: { condition: service_healthy }
    ports: ["18080:8080","19090:9090"]   # <<< меняем порты на хосте
    restart: unless-stopped

  ingester:
    build: { context: .., dockerfile: deploy/Dockerfile.ingester }
    environment:
      - APP_NAME=ingester
      - KAFKA_BROKERS=redpanda:9092
      - KAFKA_TOPIC=netintel.events.v1
      - CLICKHOUSE_ADDR=clickhouse:9000
      - CH_USER=netintel
      - CH_PASSWORD=netintel_pwd
      - CH_DATABASE=default
    depends_on:
      redpanda: { condition: service_healthy }
      clickhouse: { condition: service_healthy }
    restart: unless-stopped