version: "3.9"
services:
  zookeeper:
    image: bitnami/zookeeper:3.9
    environment: [ALLOW_ANONYMOUS_LOGIN=yes]
    ports: ["2181:2181"]

  kafka:
    image: bitnami/kafka:3.7
    depends_on: [zookeeper]
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    ports: ["9092:9092"]

  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    ports: ["9000:9000","8123:8123"]
    ulimits: { nofile: { soft: 262144, hard: 262144 } }

  collector:
    build: { context: .., dockerfile: deploy/Dockerfile.collector }
    environment:
      - APP_NAME=collector
      - HTTP_ADDR=:8080
      - METRICS_ADDR=:9090
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_TOPIC=netintel.events.v1
    depends_on: [kafka]
    ports: ["8080:8080","9090:9090"]

  ingester:
    build: { context: .., dockerfile: deploy/Dockerfile.ingester }
    environment:
      - APP_NAME=ingester
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_TOPIC=netintel.events.v1
      - CLICKHOUSE_DSN=clickhouse:9000
    depends_on: [kafka, clickhouse]
